name: Bonjour
on:
  - pull_request
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: "bonjour_node:19"  
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
      
        with:
          dockerfile: Dockerfile
      - run: docker image build --tag="${IMAGE_NAME}" ./
      - run: docker container run "${IMAGE_NAME}" npm run lint
      - run: docker image build --tag=sparkew74/sayhello:${{ github.ref_name }} ./
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          username: sparkew74
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push if on `main`
        uses: docker/login-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          push: true
          context: ./
          tags: sparkew74/sayhello:${{ github.ref_name }}